const mongoose = require("mongoose");

const Schema = mongoose.Schema;

// we build this schema based on how we defined the graphql schema (no need for id because it is autogenerated)
const appointmentSchema = new Schema({
  title: { type: String, required: true },
//   description: { type: String, required: true },
//   price: { type: Number, required: true },
//   date: { type: Date, required: true }, //dont forget to convert date to string because that's how its defined in gql schema
//   creator: {type: Schema.Types.ObjectId, ref: 'User'}
});

// first argument is the collection name and the second one is  apointer to the schema of the model
module.exports = mongoose.model('Appointment', appointmentSchema)